#!/usr/bin/env bash

# Keyboard shortcut manager
pgrep -x sxhkd > /dev/null || sxhkd &

# Wallpaper
feh --bg-fill ~/Pictures/wallpaper/splash.jpg &

# Enable right click
xinput set-prop 12 310 1 &

# Enable 4 Workspaces
bspc monitor -d I II III IV X

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"


